//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotoElectronico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCentroElectoral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCentroElectoral()
        {
            this.tbCandidatos = new HashSet<tbCandidatos>();
        }
    
        public int censo_Id { get; set; }
        public string censo_Identidad { get; set; }
        public string censo_PrimerNombre { get; set; }
        public string censo_SegundoNombre { get; set; }
        public string censo_PrimerApellido { get; set; }
        public string censo_SegundoApellido { get; set; }
        public string censo_CodigoSexo { get; set; }
        public System.DateTime censo_FechaNacimiento { get; set; }
        public int estCiv_Id { get; set; }
        public int depto_Id { get; set; }
        public int muni_Id { get; set; }
        public int aldea_Id { get; set; }
        public int pobl_Id { get; set; }
        public int censo_CodigoArea { get; set; }
        public int censo_CodigoSectorElectoral { get; set; }
        public int cenvot_Id { get; set; }
        public int censo_NumeroLinea { get; set; }
        public bool censo_EsHabilitado { get; set; }
        public Nullable<bool> censo_Voto { get; set; }
    
        public virtual tbAldeas tbAldeas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCandidatos> tbCandidatos { get; set; }
        public virtual tbDepartamentos tbDepartamentos { get; set; }
        public virtual tbEstadosCivil tbEstadosCivil { get; set; }
        public virtual tbMunicipios tbMunicipios { get; set; }
        public virtual tbPoblados tbPoblados { get; set; }
        public virtual tbCentrosVotacion tbCentrosVotacion { get; set; }
    }
}
