//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotoElectronico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCliente
    {
        public int cli_Id { get; set; }
        public string cli_Nombre { get; set; }
        public string cli_RTN { get; set; }
        public string cli_Telefono { get; set; }
        public string cli_Dirección { get; set; }
    }
}
