//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotoElectronico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMovimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMovimientos()
        {
            this.tbCandidatos = new HashSet<tbCandidatos>();
        }
    
        public int mov_Id { get; set; }
        public int part_Id { get; set; }
        public string mov_Nombre { get; set; }
        public string mov_Logo { get; set; }
        public string mov_Eslogan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCandidatos> tbCandidatos { get; set; }
        public virtual tbPartidos tbPartidos { get; set; }
    }
}
