//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotoElectronico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPoblados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPoblados()
        {
            this.tbCentroElectoral = new HashSet<tbCentroElectoral>();
        }
    
        public int pobl_Id { get; set; }
        public string pobl_Descripcion { get; set; }
        public int muni_Id { get; set; }
        public int depto_Id { get; set; }
        public int aldea_Id { get; set; }
    
        public virtual tbAldeas tbAldeas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCentroElectoral> tbCentroElectoral { get; set; }
        public virtual tbDepartamentos tbDepartamentos { get; set; }
        public virtual tbMunicipios tbMunicipios { get; set; }
    }
}
