//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotoElectronico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VotoElectronicoEntities3 : DbContext
    {
        public VotoElectronicoEntities3()
            : base("name=VotoElectronicoEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbComponentes> tbComponentes { get; set; }
        public virtual DbSet<tbModuloPantallas> tbModuloPantallas { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbRolModuloPantallas> tbRolModuloPantallas { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbCliente> tbCliente { get; set; }
        public virtual DbSet<tbAldeas> tbAldeas { get; set; }
        public virtual DbSet<tbCandidatos> tbCandidatos { get; set; }
        public virtual DbSet<tbCentroElectoral> tbCentroElectoral { get; set; }
        public virtual DbSet<tbCentrosVotacion> tbCentrosVotacion { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbEstadosCivil> tbEstadosCivil { get; set; }
        public virtual DbSet<tbMesasElectorales> tbMesasElectorales { get; set; }
        public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }
        public virtual DbSet<tbPartidos> tbPartidos { get; set; }
        public virtual DbSet<tbPoblados> tbPoblados { get; set; }
        public virtual DbSet<tbTipoCandidato> tbTipoCandidato { get; set; }
        public virtual DbSet<tbMovimientos> tbMovimientos { get; set; }
        public virtual DbSet<tbModulos> tbModulos { get; set; }
    
        public virtual ObjectResult<UDP_tbComponentes_Insert_Result> UDP_tbComponentes_Insert(string comp_Nombre)
        {
            var comp_NombreParameter = comp_Nombre != null ?
                new ObjectParameter("comp_Nombre", comp_Nombre) :
                new ObjectParameter("comp_Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbComponentes_Insert_Result>("UDP_tbComponentes_Insert", comp_NombreParameter);
        }
    
        public virtual ObjectResult<UDP_tbEstadosCivil_Insert_Result> UDP_tbEstadosCivil_Insert(string estCiv_Descripcion)
        {
            var estCiv_DescripcionParameter = estCiv_Descripcion != null ?
                new ObjectParameter("estCiv_Descripcion", estCiv_Descripcion) :
                new ObjectParameter("estCiv_Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbEstadosCivil_Insert_Result>("UDP_tbEstadosCivil_Insert", estCiv_DescripcionParameter);
        }
    
        public virtual ObjectResult<UDP_tbTipoCandidato_Insert_Result> UDP_tbTipoCandidato_Insert(string tipcan_Descripcion)
        {
            var tipcan_DescripcionParameter = tipcan_Descripcion != null ?
                new ObjectParameter("tipcan_Descripcion", tipcan_Descripcion) :
                new ObjectParameter("tipcan_Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbTipoCandidato_Insert_Result>("UDP_tbTipoCandidato_Insert", tipcan_DescripcionParameter);
        }
    
        public virtual ObjectResult<UDP_tbDepartamentos_Insert_Result> UDP_tbDepartamentos_Insert(Nullable<int> depto_Id, string depto_Descripcion)
        {
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var depto_DescripcionParameter = depto_Descripcion != null ?
                new ObjectParameter("depto_Descripcion", depto_Descripcion) :
                new ObjectParameter("depto_Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbDepartamentos_Insert_Result>("UDP_tbDepartamentos_Insert", depto_IdParameter, depto_DescripcionParameter);
        }
    
        public virtual ObjectResult<UDP_tbComponentes_Delete_Result> UDP_tbComponentes_Delete(Nullable<int> comp_Id)
        {
            var comp_IdParameter = comp_Id.HasValue ?
                new ObjectParameter("comp_Id", comp_Id) :
                new ObjectParameter("comp_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbComponentes_Delete_Result>("UDP_tbComponentes_Delete", comp_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbComponentes_Edit_Result> UDP_tbComponentes_Edit(Nullable<int> comp_Id, string comp_Nombre)
        {
            var comp_IdParameter = comp_Id.HasValue ?
                new ObjectParameter("comp_Id", comp_Id) :
                new ObjectParameter("comp_Id", typeof(int));
    
            var comp_NombreParameter = comp_Nombre != null ?
                new ObjectParameter("comp_Nombre", comp_Nombre) :
                new ObjectParameter("comp_Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbComponentes_Edit_Result>("UDP_tbComponentes_Edit", comp_IdParameter, comp_NombreParameter);
        }
    
        public virtual ObjectResult<UDP_tbDepartamentos_Delete_Result> UDP_tbDepartamentos_Delete(Nullable<int> depto_Id)
        {
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbDepartamentos_Delete_Result>("UDP_tbDepartamentos_Delete", depto_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbDepartamentos_Edit_Result> UDP_tbDepartamentos_Edit(Nullable<int> depto_Id, string depto_Descripcion)
        {
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var depto_DescripcionParameter = depto_Descripcion != null ?
                new ObjectParameter("depto_Descripcion", depto_Descripcion) :
                new ObjectParameter("depto_Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbDepartamentos_Edit_Result>("UDP_tbDepartamentos_Edit", depto_IdParameter, depto_DescripcionParameter);
        }
    
        public virtual ObjectResult<UDP_tbEstadosCivil_Delete_Result> UDP_tbEstadosCivil_Delete(Nullable<int> estCiv_Id)
        {
            var estCiv_IdParameter = estCiv_Id.HasValue ?
                new ObjectParameter("estCiv_Id", estCiv_Id) :
                new ObjectParameter("estCiv_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbEstadosCivil_Delete_Result>("UDP_tbEstadosCivil_Delete", estCiv_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbEstadosCivil_Edit_Result> UDP_tbEstadosCivil_Edit(Nullable<int> estCiv_Id, string estCiv_Descripcion)
        {
            var estCiv_IdParameter = estCiv_Id.HasValue ?
                new ObjectParameter("estCiv_Id", estCiv_Id) :
                new ObjectParameter("estCiv_Id", typeof(int));
    
            var estCiv_DescripcionParameter = estCiv_Descripcion != null ?
                new ObjectParameter("estCiv_Descripcion", estCiv_Descripcion) :
                new ObjectParameter("estCiv_Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbEstadosCivil_Edit_Result>("UDP_tbEstadosCivil_Edit", estCiv_IdParameter, estCiv_DescripcionParameter);
        }
    
        public virtual ObjectResult<UDP_tbTipoCandidato_Delete_Result> UDP_tbTipoCandidato_Delete(Nullable<int> tipcan_Id)
        {
            var tipcan_IdParameter = tipcan_Id.HasValue ?
                new ObjectParameter("tipcan_Id", tipcan_Id) :
                new ObjectParameter("tipcan_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbTipoCandidato_Delete_Result>("UDP_tbTipoCandidato_Delete", tipcan_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbTipoCandidato_Edit_Result> UDP_tbTipoCandidato_Edit(Nullable<int> tipcan_Id, string tipcan_Descripcion)
        {
            var tipcan_IdParameter = tipcan_Id.HasValue ?
                new ObjectParameter("tipcan_Id", tipcan_Id) :
                new ObjectParameter("tipcan_Id", typeof(int));
    
            var tipcan_DescripcionParameter = tipcan_Descripcion != null ?
                new ObjectParameter("tipcan_Descripcion", tipcan_Descripcion) :
                new ObjectParameter("tipcan_Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbTipoCandidato_Edit_Result>("UDP_tbTipoCandidato_Edit", tipcan_IdParameter, tipcan_DescripcionParameter);
        }
    
        public virtual ObjectResult<UDP_tbMunicipios_Insert_Result> UDP_tbMunicipios_Insert(Nullable<int> muni_Codigo, string muni_Descripcion, Nullable<int> depto_Id)
        {
            var muni_CodigoParameter = muni_Codigo.HasValue ?
                new ObjectParameter("muni_Codigo", muni_Codigo) :
                new ObjectParameter("muni_Codigo", typeof(int));
    
            var muni_DescripcionParameter = muni_Descripcion != null ?
                new ObjectParameter("muni_Descripcion", muni_Descripcion) :
                new ObjectParameter("muni_Descripcion", typeof(string));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbMunicipios_Insert_Result>("UDP_tbMunicipios_Insert", muni_CodigoParameter, muni_DescripcionParameter, depto_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbMunicipios_Edit_Result> UDP_tbMunicipios_Edit(Nullable<int> muni_Id, Nullable<int> muni_Codigo, string muni_Descripcion, Nullable<int> depto_Id)
        {
            var muni_IdParameter = muni_Id.HasValue ?
                new ObjectParameter("muni_Id", muni_Id) :
                new ObjectParameter("muni_Id", typeof(int));
    
            var muni_CodigoParameter = muni_Codigo.HasValue ?
                new ObjectParameter("muni_Codigo", muni_Codigo) :
                new ObjectParameter("muni_Codigo", typeof(int));
    
            var muni_DescripcionParameter = muni_Descripcion != null ?
                new ObjectParameter("muni_Descripcion", muni_Descripcion) :
                new ObjectParameter("muni_Descripcion", typeof(string));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbMunicipios_Edit_Result>("UDP_tbMunicipios_Edit", muni_IdParameter, muni_CodigoParameter, muni_DescripcionParameter, depto_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbMunicipios_Delete_Result1> UDP_tbMunicipios_Delete(Nullable<int> muni_Id)
        {
            var muni_IdParameter = muni_Id.HasValue ?
                new ObjectParameter("muni_Id", muni_Id) :
                new ObjectParameter("muni_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbMunicipios_Delete_Result1>("UDP_tbMunicipios_Delete", muni_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbAldeas_Insert_Result> UDP_tbAldeas_Insert(string aldea_Descripcion, Nullable<int> muni_Id, Nullable<int> depto_Id)
        {
            var aldea_DescripcionParameter = aldea_Descripcion != null ?
                new ObjectParameter("aldea_Descripcion", aldea_Descripcion) :
                new ObjectParameter("aldea_Descripcion", typeof(string));
    
            var muni_IdParameter = muni_Id.HasValue ?
                new ObjectParameter("muni_Id", muni_Id) :
                new ObjectParameter("muni_Id", typeof(int));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbAldeas_Insert_Result>("UDP_tbAldeas_Insert", aldea_DescripcionParameter, muni_IdParameter, depto_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbAldeas_Edit_Result> UDP_tbAldeas_Edit(Nullable<int> aldea_Id, string aldea_Descripcion, Nullable<int> muni_Id, Nullable<int> depto_Id)
        {
            var aldea_IdParameter = aldea_Id.HasValue ?
                new ObjectParameter("aldea_Id", aldea_Id) :
                new ObjectParameter("aldea_Id", typeof(int));
    
            var aldea_DescripcionParameter = aldea_Descripcion != null ?
                new ObjectParameter("aldea_Descripcion", aldea_Descripcion) :
                new ObjectParameter("aldea_Descripcion", typeof(string));
    
            var muni_IdParameter = muni_Id.HasValue ?
                new ObjectParameter("muni_Id", muni_Id) :
                new ObjectParameter("muni_Id", typeof(int));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbAldeas_Edit_Result>("UDP_tbAldeas_Edit", aldea_IdParameter, aldea_DescripcionParameter, muni_IdParameter, depto_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbAldeas_Delete_Result> UDP_tbAldeas_Delete(Nullable<int> aldea_Id)
        {
            var aldea_IdParameter = aldea_Id.HasValue ?
                new ObjectParameter("aldea_Id", aldea_Id) :
                new ObjectParameter("aldea_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbAldeas_Delete_Result>("UDP_tbAldeas_Delete", aldea_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbPoblados_Insert_Result> UDP_tbPoblados_Insert(string pobl_Descripcion, Nullable<int> muni_Id, Nullable<int> depto_Id, Nullable<int> aldea_Id)
        {
            var pobl_DescripcionParameter = pobl_Descripcion != null ?
                new ObjectParameter("pobl_Descripcion", pobl_Descripcion) :
                new ObjectParameter("pobl_Descripcion", typeof(string));
    
            var muni_IdParameter = muni_Id.HasValue ?
                new ObjectParameter("muni_Id", muni_Id) :
                new ObjectParameter("muni_Id", typeof(int));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var aldea_IdParameter = aldea_Id.HasValue ?
                new ObjectParameter("aldea_Id", aldea_Id) :
                new ObjectParameter("aldea_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbPoblados_Insert_Result>("UDP_tbPoblados_Insert", pobl_DescripcionParameter, muni_IdParameter, depto_IdParameter, aldea_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbPoblados_Edit_Result> UDP_tbPoblados_Edit(Nullable<int> pobl_Id, string pobl_Descripcion, Nullable<int> muni_Id, Nullable<int> depto_Id, Nullable<int> aldea_Id)
        {
            var pobl_IdParameter = pobl_Id.HasValue ?
                new ObjectParameter("pobl_Id", pobl_Id) :
                new ObjectParameter("pobl_Id", typeof(int));
    
            var pobl_DescripcionParameter = pobl_Descripcion != null ?
                new ObjectParameter("pobl_Descripcion", pobl_Descripcion) :
                new ObjectParameter("pobl_Descripcion", typeof(string));
    
            var muni_IdParameter = muni_Id.HasValue ?
                new ObjectParameter("muni_Id", muni_Id) :
                new ObjectParameter("muni_Id", typeof(int));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var aldea_IdParameter = aldea_Id.HasValue ?
                new ObjectParameter("aldea_Id", aldea_Id) :
                new ObjectParameter("aldea_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbPoblados_Edit_Result>("UDP_tbPoblados_Edit", pobl_IdParameter, pobl_DescripcionParameter, muni_IdParameter, depto_IdParameter, aldea_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbPoblados_Delete_Result> UDP_tbPoblados_Delete(Nullable<int> pobl_Id)
        {
            var pobl_IdParameter = pobl_Id.HasValue ?
                new ObjectParameter("pobl_Id", pobl_Id) :
                new ObjectParameter("pobl_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbPoblados_Delete_Result>("UDP_tbPoblados_Delete", pobl_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbCentrosVotacion_Insert_Result> UDP_tbCentrosVotacion_Insert(Nullable<int> depto_Id, Nullable<int> muni_Id, Nullable<int> cenvot_CodigoArea, Nullable<int> cenvot_CodigoSectorElectoral, string cenvot_Nombre, Nullable<double> cenvot_Latitud, Nullable<double> cenvot_Longitud, Nullable<int> cenvot_TotalMesas)
        {
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var muni_IdParameter = muni_Id.HasValue ?
                new ObjectParameter("muni_Id", muni_Id) :
                new ObjectParameter("muni_Id", typeof(int));
    
            var cenvot_CodigoAreaParameter = cenvot_CodigoArea.HasValue ?
                new ObjectParameter("cenvot_CodigoArea", cenvot_CodigoArea) :
                new ObjectParameter("cenvot_CodigoArea", typeof(int));
    
            var cenvot_CodigoSectorElectoralParameter = cenvot_CodigoSectorElectoral.HasValue ?
                new ObjectParameter("cenvot_CodigoSectorElectoral", cenvot_CodigoSectorElectoral) :
                new ObjectParameter("cenvot_CodigoSectorElectoral", typeof(int));
    
            var cenvot_NombreParameter = cenvot_Nombre != null ?
                new ObjectParameter("cenvot_Nombre", cenvot_Nombre) :
                new ObjectParameter("cenvot_Nombre", typeof(string));
    
            var cenvot_LatitudParameter = cenvot_Latitud.HasValue ?
                new ObjectParameter("cenvot_Latitud", cenvot_Latitud) :
                new ObjectParameter("cenvot_Latitud", typeof(double));
    
            var cenvot_LongitudParameter = cenvot_Longitud.HasValue ?
                new ObjectParameter("cenvot_Longitud", cenvot_Longitud) :
                new ObjectParameter("cenvot_Longitud", typeof(double));
    
            var cenvot_TotalMesasParameter = cenvot_TotalMesas.HasValue ?
                new ObjectParameter("cenvot_TotalMesas", cenvot_TotalMesas) :
                new ObjectParameter("cenvot_TotalMesas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbCentrosVotacion_Insert_Result>("UDP_tbCentrosVotacion_Insert", depto_IdParameter, muni_IdParameter, cenvot_CodigoAreaParameter, cenvot_CodigoSectorElectoralParameter, cenvot_NombreParameter, cenvot_LatitudParameter, cenvot_LongitudParameter, cenvot_TotalMesasParameter);
        }
    
        public virtual ObjectResult<UDP_tbCentrosVotacion_Edit_Result> UDP_tbCentrosVotacion_Edit(Nullable<int> cenvot_Id, Nullable<int> depto_Id, Nullable<int> muni_Id, Nullable<int> cenvot_CodigoArea, Nullable<int> cenvot_CodigoSectorElectoral, string cenvot_Nombre, Nullable<double> cenvot_Latitud, Nullable<double> cenvot_Longitud, Nullable<int> cenvot_TotalMesas)
        {
            var cenvot_IdParameter = cenvot_Id.HasValue ?
                new ObjectParameter("cenvot_Id", cenvot_Id) :
                new ObjectParameter("cenvot_Id", typeof(int));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var muni_IdParameter = muni_Id.HasValue ?
                new ObjectParameter("muni_Id", muni_Id) :
                new ObjectParameter("muni_Id", typeof(int));
    
            var cenvot_CodigoAreaParameter = cenvot_CodigoArea.HasValue ?
                new ObjectParameter("cenvot_CodigoArea", cenvot_CodigoArea) :
                new ObjectParameter("cenvot_CodigoArea", typeof(int));
    
            var cenvot_CodigoSectorElectoralParameter = cenvot_CodigoSectorElectoral.HasValue ?
                new ObjectParameter("cenvot_CodigoSectorElectoral", cenvot_CodigoSectorElectoral) :
                new ObjectParameter("cenvot_CodigoSectorElectoral", typeof(int));
    
            var cenvot_NombreParameter = cenvot_Nombre != null ?
                new ObjectParameter("cenvot_Nombre", cenvot_Nombre) :
                new ObjectParameter("cenvot_Nombre", typeof(string));
    
            var cenvot_LatitudParameter = cenvot_Latitud.HasValue ?
                new ObjectParameter("cenvot_Latitud", cenvot_Latitud) :
                new ObjectParameter("cenvot_Latitud", typeof(double));
    
            var cenvot_LongitudParameter = cenvot_Longitud.HasValue ?
                new ObjectParameter("cenvot_Longitud", cenvot_Longitud) :
                new ObjectParameter("cenvot_Longitud", typeof(double));
    
            var cenvot_TotalMesasParameter = cenvot_TotalMesas.HasValue ?
                new ObjectParameter("cenvot_TotalMesas", cenvot_TotalMesas) :
                new ObjectParameter("cenvot_TotalMesas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbCentrosVotacion_Edit_Result>("UDP_tbCentrosVotacion_Edit", cenvot_IdParameter, depto_IdParameter, muni_IdParameter, cenvot_CodigoAreaParameter, cenvot_CodigoSectorElectoralParameter, cenvot_NombreParameter, cenvot_LatitudParameter, cenvot_LongitudParameter, cenvot_TotalMesasParameter);
        }
    
        public virtual ObjectResult<UDP_tbCentrosVotacion_Delete_Result> UDP_tbCentrosVotacion_Delete(Nullable<int> cenvot_Id)
        {
            var cenvot_IdParameter = cenvot_Id.HasValue ?
                new ObjectParameter("cenvot_Id", cenvot_Id) :
                new ObjectParameter("cenvot_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbCentrosVotacion_Delete_Result>("UDP_tbCentrosVotacion_Delete", cenvot_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbMesasElectorales_Insert_Result> UDP_tbMesasElectorales_Insert(Nullable<int> cenvot_Id)
        {
            var cenvot_IdParameter = cenvot_Id.HasValue ?
                new ObjectParameter("cenvot_Id", cenvot_Id) :
                new ObjectParameter("cenvot_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbMesasElectorales_Insert_Result>("UDP_tbMesasElectorales_Insert", cenvot_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbMesasElectorales_Edit_Result> UDP_tbMesasElectorales_Edit(Nullable<int> mesa_Id, Nullable<int> cenvot_Id)
        {
            var mesa_IdParameter = mesa_Id.HasValue ?
                new ObjectParameter("mesa_Id", mesa_Id) :
                new ObjectParameter("mesa_Id", typeof(int));
    
            var cenvot_IdParameter = cenvot_Id.HasValue ?
                new ObjectParameter("cenvot_Id", cenvot_Id) :
                new ObjectParameter("cenvot_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbMesasElectorales_Edit_Result>("UDP_tbMesasElectorales_Edit", mesa_IdParameter, cenvot_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbMesasElectorales_Delete_Result> UDP_tbMesasElectorales_Delete(Nullable<int> mesa_Id)
        {
            var mesa_IdParameter = mesa_Id.HasValue ?
                new ObjectParameter("mesa_Id", mesa_Id) :
                new ObjectParameter("mesa_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbMesasElectorales_Delete_Result>("UDP_tbMesasElectorales_Delete", mesa_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbCentroElectoral_Insert_Result> UDP_tbCentroElectoral_Insert(string censo_Identidad, string censo_PrimerNombre, string censo_SegundoNombre, string censo_PrimerApellido, string censo_SegundoApellido, string censo_CodigoSexo, Nullable<System.DateTime> censo_FechaNacimiento, Nullable<int> estCiv_Id, Nullable<int> depto_Id, Nullable<int> muni_Id, Nullable<int> aldea_Id, Nullable<int> pobl_Id, Nullable<int> censo_CodigoArea, Nullable<int> censo_CodigoSectorElectoral, Nullable<int> cenvot_Id, Nullable<int> censo_NumeroLinea, Nullable<bool> censo_EsHabilitado)
        {
            var censo_IdentidadParameter = censo_Identidad != null ?
                new ObjectParameter("censo_Identidad", censo_Identidad) :
                new ObjectParameter("censo_Identidad", typeof(string));
    
            var censo_PrimerNombreParameter = censo_PrimerNombre != null ?
                new ObjectParameter("censo_PrimerNombre", censo_PrimerNombre) :
                new ObjectParameter("censo_PrimerNombre", typeof(string));
    
            var censo_SegundoNombreParameter = censo_SegundoNombre != null ?
                new ObjectParameter("censo_SegundoNombre", censo_SegundoNombre) :
                new ObjectParameter("censo_SegundoNombre", typeof(string));
    
            var censo_PrimerApellidoParameter = censo_PrimerApellido != null ?
                new ObjectParameter("censo_PrimerApellido", censo_PrimerApellido) :
                new ObjectParameter("censo_PrimerApellido", typeof(string));
    
            var censo_SegundoApellidoParameter = censo_SegundoApellido != null ?
                new ObjectParameter("censo_SegundoApellido", censo_SegundoApellido) :
                new ObjectParameter("censo_SegundoApellido", typeof(string));
    
            var censo_CodigoSexoParameter = censo_CodigoSexo != null ?
                new ObjectParameter("censo_CodigoSexo", censo_CodigoSexo) :
                new ObjectParameter("censo_CodigoSexo", typeof(string));
    
            var censo_FechaNacimientoParameter = censo_FechaNacimiento.HasValue ?
                new ObjectParameter("censo_FechaNacimiento", censo_FechaNacimiento) :
                new ObjectParameter("censo_FechaNacimiento", typeof(System.DateTime));
    
            var estCiv_IdParameter = estCiv_Id.HasValue ?
                new ObjectParameter("estCiv_Id", estCiv_Id) :
                new ObjectParameter("estCiv_Id", typeof(int));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var muni_IdParameter = muni_Id.HasValue ?
                new ObjectParameter("muni_Id", muni_Id) :
                new ObjectParameter("muni_Id", typeof(int));
    
            var aldea_IdParameter = aldea_Id.HasValue ?
                new ObjectParameter("aldea_Id", aldea_Id) :
                new ObjectParameter("aldea_Id", typeof(int));
    
            var pobl_IdParameter = pobl_Id.HasValue ?
                new ObjectParameter("pobl_Id", pobl_Id) :
                new ObjectParameter("pobl_Id", typeof(int));
    
            var censo_CodigoAreaParameter = censo_CodigoArea.HasValue ?
                new ObjectParameter("censo_CodigoArea", censo_CodigoArea) :
                new ObjectParameter("censo_CodigoArea", typeof(int));
    
            var censo_CodigoSectorElectoralParameter = censo_CodigoSectorElectoral.HasValue ?
                new ObjectParameter("censo_CodigoSectorElectoral", censo_CodigoSectorElectoral) :
                new ObjectParameter("censo_CodigoSectorElectoral", typeof(int));
    
            var cenvot_IdParameter = cenvot_Id.HasValue ?
                new ObjectParameter("cenvot_Id", cenvot_Id) :
                new ObjectParameter("cenvot_Id", typeof(int));
    
            var censo_NumeroLineaParameter = censo_NumeroLinea.HasValue ?
                new ObjectParameter("censo_NumeroLinea", censo_NumeroLinea) :
                new ObjectParameter("censo_NumeroLinea", typeof(int));
    
            var censo_EsHabilitadoParameter = censo_EsHabilitado.HasValue ?
                new ObjectParameter("censo_EsHabilitado", censo_EsHabilitado) :
                new ObjectParameter("censo_EsHabilitado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbCentroElectoral_Insert_Result>("UDP_tbCentroElectoral_Insert", censo_IdentidadParameter, censo_PrimerNombreParameter, censo_SegundoNombreParameter, censo_PrimerApellidoParameter, censo_SegundoApellidoParameter, censo_CodigoSexoParameter, censo_FechaNacimientoParameter, estCiv_IdParameter, depto_IdParameter, muni_IdParameter, aldea_IdParameter, pobl_IdParameter, censo_CodigoAreaParameter, censo_CodigoSectorElectoralParameter, cenvot_IdParameter, censo_NumeroLineaParameter, censo_EsHabilitadoParameter);
        }
    
        public virtual ObjectResult<UDP_tbCentroElectoral_Edit_Result> UDP_tbCentroElectoral_Edit(Nullable<int> censo_Id, string censo_Identidad, string censo_PrimerNombre, string censo_SegundoNombre, string censo_PrimerApellido, string censo_SegundoApellido, string censo_CodigoSexo, Nullable<System.DateTime> censo_FechaNacimiento, Nullable<int> estCiv_Id, Nullable<int> depto_Id, Nullable<int> muni_Id, Nullable<int> aldea_Id, Nullable<int> pobl_Id, Nullable<int> censo_CodigoArea, Nullable<int> censo_CodigoSectorElectoral, Nullable<int> cenvot_Id, Nullable<int> censo_NumeroLinea, Nullable<bool> censo_EsHabilitado)
        {
            var censo_IdParameter = censo_Id.HasValue ?
                new ObjectParameter("censo_Id", censo_Id) :
                new ObjectParameter("censo_Id", typeof(int));
    
            var censo_IdentidadParameter = censo_Identidad != null ?
                new ObjectParameter("censo_Identidad", censo_Identidad) :
                new ObjectParameter("censo_Identidad", typeof(string));
    
            var censo_PrimerNombreParameter = censo_PrimerNombre != null ?
                new ObjectParameter("censo_PrimerNombre", censo_PrimerNombre) :
                new ObjectParameter("censo_PrimerNombre", typeof(string));
    
            var censo_SegundoNombreParameter = censo_SegundoNombre != null ?
                new ObjectParameter("censo_SegundoNombre", censo_SegundoNombre) :
                new ObjectParameter("censo_SegundoNombre", typeof(string));
    
            var censo_PrimerApellidoParameter = censo_PrimerApellido != null ?
                new ObjectParameter("censo_PrimerApellido", censo_PrimerApellido) :
                new ObjectParameter("censo_PrimerApellido", typeof(string));
    
            var censo_SegundoApellidoParameter = censo_SegundoApellido != null ?
                new ObjectParameter("censo_SegundoApellido", censo_SegundoApellido) :
                new ObjectParameter("censo_SegundoApellido", typeof(string));
    
            var censo_CodigoSexoParameter = censo_CodigoSexo != null ?
                new ObjectParameter("censo_CodigoSexo", censo_CodigoSexo) :
                new ObjectParameter("censo_CodigoSexo", typeof(string));
    
            var censo_FechaNacimientoParameter = censo_FechaNacimiento.HasValue ?
                new ObjectParameter("censo_FechaNacimiento", censo_FechaNacimiento) :
                new ObjectParameter("censo_FechaNacimiento", typeof(System.DateTime));
    
            var estCiv_IdParameter = estCiv_Id.HasValue ?
                new ObjectParameter("estCiv_Id", estCiv_Id) :
                new ObjectParameter("estCiv_Id", typeof(int));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var muni_IdParameter = muni_Id.HasValue ?
                new ObjectParameter("muni_Id", muni_Id) :
                new ObjectParameter("muni_Id", typeof(int));
    
            var aldea_IdParameter = aldea_Id.HasValue ?
                new ObjectParameter("aldea_Id", aldea_Id) :
                new ObjectParameter("aldea_Id", typeof(int));
    
            var pobl_IdParameter = pobl_Id.HasValue ?
                new ObjectParameter("pobl_Id", pobl_Id) :
                new ObjectParameter("pobl_Id", typeof(int));
    
            var censo_CodigoAreaParameter = censo_CodigoArea.HasValue ?
                new ObjectParameter("censo_CodigoArea", censo_CodigoArea) :
                new ObjectParameter("censo_CodigoArea", typeof(int));
    
            var censo_CodigoSectorElectoralParameter = censo_CodigoSectorElectoral.HasValue ?
                new ObjectParameter("censo_CodigoSectorElectoral", censo_CodigoSectorElectoral) :
                new ObjectParameter("censo_CodigoSectorElectoral", typeof(int));
    
            var cenvot_IdParameter = cenvot_Id.HasValue ?
                new ObjectParameter("cenvot_Id", cenvot_Id) :
                new ObjectParameter("cenvot_Id", typeof(int));
    
            var censo_NumeroLineaParameter = censo_NumeroLinea.HasValue ?
                new ObjectParameter("censo_NumeroLinea", censo_NumeroLinea) :
                new ObjectParameter("censo_NumeroLinea", typeof(int));
    
            var censo_EsHabilitadoParameter = censo_EsHabilitado.HasValue ?
                new ObjectParameter("censo_EsHabilitado", censo_EsHabilitado) :
                new ObjectParameter("censo_EsHabilitado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbCentroElectoral_Edit_Result>("UDP_tbCentroElectoral_Edit", censo_IdParameter, censo_IdentidadParameter, censo_PrimerNombreParameter, censo_SegundoNombreParameter, censo_PrimerApellidoParameter, censo_SegundoApellidoParameter, censo_CodigoSexoParameter, censo_FechaNacimientoParameter, estCiv_IdParameter, depto_IdParameter, muni_IdParameter, aldea_IdParameter, pobl_IdParameter, censo_CodigoAreaParameter, censo_CodigoSectorElectoralParameter, cenvot_IdParameter, censo_NumeroLineaParameter, censo_EsHabilitadoParameter);
        }
    
        public virtual ObjectResult<UDP_tbCentroElectoral_Delete_Result> UDP_tbCentroElectoral_Delete(Nullable<int> censo_Id)
        {
            var censo_IdParameter = censo_Id.HasValue ?
                new ObjectParameter("censo_Id", censo_Id) :
                new ObjectParameter("censo_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbCentroElectoral_Delete_Result>("UDP_tbCentroElectoral_Delete", censo_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbCandidatos_Insert_Result> UDP_tbCandidatos_Insert(Nullable<int> part_Id, Nullable<int> mov_Id, Nullable<int> tipcan_Id, Nullable<int> censo_Id, Nullable<int> depto_Id, Nullable<int> muni_Id, Nullable<int> cand_Posicion)
        {
            var part_IdParameter = part_Id.HasValue ?
                new ObjectParameter("part_Id", part_Id) :
                new ObjectParameter("part_Id", typeof(int));
    
            var mov_IdParameter = mov_Id.HasValue ?
                new ObjectParameter("mov_Id", mov_Id) :
                new ObjectParameter("mov_Id", typeof(int));
    
            var tipcan_IdParameter = tipcan_Id.HasValue ?
                new ObjectParameter("tipcan_Id", tipcan_Id) :
                new ObjectParameter("tipcan_Id", typeof(int));
    
            var censo_IdParameter = censo_Id.HasValue ?
                new ObjectParameter("censo_Id", censo_Id) :
                new ObjectParameter("censo_Id", typeof(int));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var muni_IdParameter = muni_Id.HasValue ?
                new ObjectParameter("muni_Id", muni_Id) :
                new ObjectParameter("muni_Id", typeof(int));
    
            var cand_PosicionParameter = cand_Posicion.HasValue ?
                new ObjectParameter("cand_Posicion", cand_Posicion) :
                new ObjectParameter("cand_Posicion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbCandidatos_Insert_Result>("UDP_tbCandidatos_Insert", part_IdParameter, mov_IdParameter, tipcan_IdParameter, censo_IdParameter, depto_IdParameter, muni_IdParameter, cand_PosicionParameter);
        }
    
        public virtual ObjectResult<UDP_tbCandidatos_Edit_Result> UDP_tbCandidatos_Edit(Nullable<int> cand_Id, Nullable<int> part_Id, Nullable<int> mov_Id, Nullable<int> tipcan_Id, Nullable<int> censo_Id, Nullable<int> depto_Id, Nullable<int> muni_Id, Nullable<int> cand_Posicion)
        {
            var cand_IdParameter = cand_Id.HasValue ?
                new ObjectParameter("cand_Id", cand_Id) :
                new ObjectParameter("cand_Id", typeof(int));
    
            var part_IdParameter = part_Id.HasValue ?
                new ObjectParameter("part_Id", part_Id) :
                new ObjectParameter("part_Id", typeof(int));
    
            var mov_IdParameter = mov_Id.HasValue ?
                new ObjectParameter("mov_Id", mov_Id) :
                new ObjectParameter("mov_Id", typeof(int));
    
            var tipcan_IdParameter = tipcan_Id.HasValue ?
                new ObjectParameter("tipcan_Id", tipcan_Id) :
                new ObjectParameter("tipcan_Id", typeof(int));
    
            var censo_IdParameter = censo_Id.HasValue ?
                new ObjectParameter("censo_Id", censo_Id) :
                new ObjectParameter("censo_Id", typeof(int));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var muni_IdParameter = muni_Id.HasValue ?
                new ObjectParameter("muni_Id", muni_Id) :
                new ObjectParameter("muni_Id", typeof(int));
    
            var cand_PosicionParameter = cand_Posicion.HasValue ?
                new ObjectParameter("cand_Posicion", cand_Posicion) :
                new ObjectParameter("cand_Posicion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbCandidatos_Edit_Result>("UDP_tbCandidatos_Edit", cand_IdParameter, part_IdParameter, mov_IdParameter, tipcan_IdParameter, censo_IdParameter, depto_IdParameter, muni_IdParameter, cand_PosicionParameter);
        }
    
        public virtual ObjectResult<UDP_tbCandidatos_Delete_Result> UDP_tbCandidatos_Delete(Nullable<int> cand_Id)
        {
            var cand_IdParameter = cand_Id.HasValue ?
                new ObjectParameter("cand_Id", cand_Id) :
                new ObjectParameter("cand_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbCandidatos_Delete_Result>("UDP_tbCandidatos_Delete", cand_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbPartidos_Insert_Result> UDP_tbPartidos_Insert(string part_Nombre, string part_Siglas, string part_Sede, string part_ColorEmblema, string part_Logo)
        {
            var part_NombreParameter = part_Nombre != null ?
                new ObjectParameter("part_Nombre", part_Nombre) :
                new ObjectParameter("part_Nombre", typeof(string));
    
            var part_SiglasParameter = part_Siglas != null ?
                new ObjectParameter("part_Siglas", part_Siglas) :
                new ObjectParameter("part_Siglas", typeof(string));
    
            var part_SedeParameter = part_Sede != null ?
                new ObjectParameter("part_Sede", part_Sede) :
                new ObjectParameter("part_Sede", typeof(string));
    
            var part_ColorEmblemaParameter = part_ColorEmblema != null ?
                new ObjectParameter("part_ColorEmblema", part_ColorEmblema) :
                new ObjectParameter("part_ColorEmblema", typeof(string));
    
            var part_LogoParameter = part_Logo != null ?
                new ObjectParameter("part_Logo", part_Logo) :
                new ObjectParameter("part_Logo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbPartidos_Insert_Result>("UDP_tbPartidos_Insert", part_NombreParameter, part_SiglasParameter, part_SedeParameter, part_ColorEmblemaParameter, part_LogoParameter);
        }
    
        public virtual ObjectResult<UDP_tbPartidos_Edit_Result> UDP_tbPartidos_Edit(Nullable<int> part_Id, string part_Nombre, string part_Siglas, string part_Sede, string part_ColorEmblema, string part_Logo)
        {
            var part_IdParameter = part_Id.HasValue ?
                new ObjectParameter("part_Id", part_Id) :
                new ObjectParameter("part_Id", typeof(int));
    
            var part_NombreParameter = part_Nombre != null ?
                new ObjectParameter("part_Nombre", part_Nombre) :
                new ObjectParameter("part_Nombre", typeof(string));
    
            var part_SiglasParameter = part_Siglas != null ?
                new ObjectParameter("part_Siglas", part_Siglas) :
                new ObjectParameter("part_Siglas", typeof(string));
    
            var part_SedeParameter = part_Sede != null ?
                new ObjectParameter("part_Sede", part_Sede) :
                new ObjectParameter("part_Sede", typeof(string));
    
            var part_ColorEmblemaParameter = part_ColorEmblema != null ?
                new ObjectParameter("part_ColorEmblema", part_ColorEmblema) :
                new ObjectParameter("part_ColorEmblema", typeof(string));
    
            var part_LogoParameter = part_Logo != null ?
                new ObjectParameter("part_Logo", part_Logo) :
                new ObjectParameter("part_Logo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbPartidos_Edit_Result>("UDP_tbPartidos_Edit", part_IdParameter, part_NombreParameter, part_SiglasParameter, part_SedeParameter, part_ColorEmblemaParameter, part_LogoParameter);
        }
    
        public virtual ObjectResult<string> UDP_tbPartidos_Delete(Nullable<int> part_Id)
        {
            var part_IdParameter = part_Id.HasValue ?
                new ObjectParameter("part_Id", part_Id) :
                new ObjectParameter("part_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_tbPartidos_Delete", part_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbModulos_Insert_Result> UDP_tbModulos_Insert(Nullable<int> comp_Id, string mod_Nombre)
        {
            var comp_IdParameter = comp_Id.HasValue ?
                new ObjectParameter("comp_Id", comp_Id) :
                new ObjectParameter("comp_Id", typeof(int));
    
            var mod_NombreParameter = mod_Nombre != null ?
                new ObjectParameter("mod_Nombre", mod_Nombre) :
                new ObjectParameter("mod_Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbModulos_Insert_Result>("UDP_tbModulos_Insert", comp_IdParameter, mod_NombreParameter);
        }
    
        public virtual ObjectResult<UDP_tbModulos_Edit_Result> UDP_tbModulos_Edit(Nullable<int> mod_Id, Nullable<int> comp_Id, string mod_Nombre)
        {
            var mod_IdParameter = mod_Id.HasValue ?
                new ObjectParameter("mod_Id", mod_Id) :
                new ObjectParameter("mod_Id", typeof(int));
    
            var comp_IdParameter = comp_Id.HasValue ?
                new ObjectParameter("comp_Id", comp_Id) :
                new ObjectParameter("comp_Id", typeof(int));
    
            var mod_NombreParameter = mod_Nombre != null ?
                new ObjectParameter("mod_Nombre", mod_Nombre) :
                new ObjectParameter("mod_Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbModulos_Edit_Result>("UDP_tbModulos_Edit", mod_IdParameter, comp_IdParameter, mod_NombreParameter);
        }
    
        public virtual ObjectResult<UDP_tbModulos_Delete_Result> UDP_tbModulos_Delete(Nullable<int> mod_Id)
        {
            var mod_IdParameter = mod_Id.HasValue ?
                new ObjectParameter("mod_Id", mod_Id) :
                new ObjectParameter("mod_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbModulos_Delete_Result>("UDP_tbModulos_Delete", mod_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbModuloPantallas_Delete_Result> UDP_tbModuloPantallas_Delete(Nullable<int> modpan_Id)
        {
            var modpan_IdParameter = modpan_Id.HasValue ?
                new ObjectParameter("modpan_Id", modpan_Id) :
                new ObjectParameter("modpan_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbModuloPantallas_Delete_Result>("UDP_tbModuloPantallas_Delete", modpan_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbModuloPantallas_Edit_Result> UDP_tbModuloPantallas_Edit(Nullable<int> modpan_Id, Nullable<int> mod_Id, string modpan_Nombre)
        {
            var modpan_IdParameter = modpan_Id.HasValue ?
                new ObjectParameter("modpan_Id", modpan_Id) :
                new ObjectParameter("modpan_Id", typeof(int));
    
            var mod_IdParameter = mod_Id.HasValue ?
                new ObjectParameter("mod_Id", mod_Id) :
                new ObjectParameter("mod_Id", typeof(int));
    
            var modpan_NombreParameter = modpan_Nombre != null ?
                new ObjectParameter("modpan_Nombre", modpan_Nombre) :
                new ObjectParameter("modpan_Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbModuloPantallas_Edit_Result>("UDP_tbModuloPantallas_Edit", modpan_IdParameter, mod_IdParameter, modpan_NombreParameter);
        }
    
        public virtual ObjectResult<UDP_tbModuloPantallas_Insert_Result> UDP_tbModuloPantallas_Insert(Nullable<int> mod_Id, string modpan_Nombre)
        {
            var mod_IdParameter = mod_Id.HasValue ?
                new ObjectParameter("mod_Id", mod_Id) :
                new ObjectParameter("mod_Id", typeof(int));
    
            var modpan_NombreParameter = modpan_Nombre != null ?
                new ObjectParameter("modpan_Nombre", modpan_Nombre) :
                new ObjectParameter("modpan_Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbModuloPantallas_Insert_Result>("UDP_tbModuloPantallas_Insert", mod_IdParameter, modpan_NombreParameter);
        }
    
        public virtual ObjectResult<UDP_tbUsuario_Delete_Result> UDP_tbUsuario_Delete(Nullable<int> usu_Id)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbUsuario_Delete_Result>("UDP_tbUsuario_Delete", usu_IdParameter);
        }
    
        public virtual ObjectResult<UDP_tbUsuario_Edit_Result> UDP_tbUsuario_Edit(Nullable<int> usu_Id, string usu_Identidad, string usu_PrimerNombre, string usu_PrimerApellido, string usu_SegundoNombre, string usu_SegundoApellido, string usu_Telefono, Nullable<int> rol_Id, Nullable<bool> usu_EsActivo)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var usu_IdentidadParameter = usu_Identidad != null ?
                new ObjectParameter("usu_Identidad", usu_Identidad) :
                new ObjectParameter("usu_Identidad", typeof(string));
    
            var usu_PrimerNombreParameter = usu_PrimerNombre != null ?
                new ObjectParameter("usu_PrimerNombre", usu_PrimerNombre) :
                new ObjectParameter("usu_PrimerNombre", typeof(string));
    
            var usu_PrimerApellidoParameter = usu_PrimerApellido != null ?
                new ObjectParameter("usu_PrimerApellido", usu_PrimerApellido) :
                new ObjectParameter("usu_PrimerApellido", typeof(string));
    
            var usu_SegundoNombreParameter = usu_SegundoNombre != null ?
                new ObjectParameter("usu_SegundoNombre", usu_SegundoNombre) :
                new ObjectParameter("usu_SegundoNombre", typeof(string));
    
            var usu_SegundoApellidoParameter = usu_SegundoApellido != null ?
                new ObjectParameter("usu_SegundoApellido", usu_SegundoApellido) :
                new ObjectParameter("usu_SegundoApellido", typeof(string));
    
            var usu_TelefonoParameter = usu_Telefono != null ?
                new ObjectParameter("usu_Telefono", usu_Telefono) :
                new ObjectParameter("usu_Telefono", typeof(string));
    
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var usu_EsActivoParameter = usu_EsActivo.HasValue ?
                new ObjectParameter("usu_EsActivo", usu_EsActivo) :
                new ObjectParameter("usu_EsActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbUsuario_Edit_Result>("UDP_tbUsuario_Edit", usu_IdParameter, usu_IdentidadParameter, usu_PrimerNombreParameter, usu_PrimerApellidoParameter, usu_SegundoNombreParameter, usu_SegundoApellidoParameter, usu_TelefonoParameter, rol_IdParameter, usu_EsActivoParameter);
        }
    
        public virtual ObjectResult<UDP_tbUsuario_Insert_Result> UDP_tbUsuario_Insert(string usu_Identidad, string usu_PrimerNombre, string usu_PrimerApellido, string usu_SegundoNombre, string usu_SegundoApellido, string usu_Telefono, string usu_Contraseña, Nullable<int> rol_Id, Nullable<bool> usu_EsActivo)
        {
            var usu_IdentidadParameter = usu_Identidad != null ?
                new ObjectParameter("usu_Identidad", usu_Identidad) :
                new ObjectParameter("usu_Identidad", typeof(string));
    
            var usu_PrimerNombreParameter = usu_PrimerNombre != null ?
                new ObjectParameter("usu_PrimerNombre", usu_PrimerNombre) :
                new ObjectParameter("usu_PrimerNombre", typeof(string));
    
            var usu_PrimerApellidoParameter = usu_PrimerApellido != null ?
                new ObjectParameter("usu_PrimerApellido", usu_PrimerApellido) :
                new ObjectParameter("usu_PrimerApellido", typeof(string));
    
            var usu_SegundoNombreParameter = usu_SegundoNombre != null ?
                new ObjectParameter("usu_SegundoNombre", usu_SegundoNombre) :
                new ObjectParameter("usu_SegundoNombre", typeof(string));
    
            var usu_SegundoApellidoParameter = usu_SegundoApellido != null ?
                new ObjectParameter("usu_SegundoApellido", usu_SegundoApellido) :
                new ObjectParameter("usu_SegundoApellido", typeof(string));
    
            var usu_TelefonoParameter = usu_Telefono != null ?
                new ObjectParameter("usu_Telefono", usu_Telefono) :
                new ObjectParameter("usu_Telefono", typeof(string));
    
            var usu_ContraseñaParameter = usu_Contraseña != null ?
                new ObjectParameter("usu_Contraseña", usu_Contraseña) :
                new ObjectParameter("usu_Contraseña", typeof(string));
    
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var usu_EsActivoParameter = usu_EsActivo.HasValue ?
                new ObjectParameter("usu_EsActivo", usu_EsActivo) :
                new ObjectParameter("usu_EsActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_tbUsuario_Insert_Result>("UDP_tbUsuario_Insert", usu_IdentidadParameter, usu_PrimerNombreParameter, usu_PrimerApellidoParameter, usu_SegundoNombreParameter, usu_SegundoApellidoParameter, usu_TelefonoParameter, usu_ContraseñaParameter, rol_IdParameter, usu_EsActivoParameter);
        }
    }
}
